### ISSUE TITLE
x/h-mapping does not convert for already-written text

### ISSUE THREAD

**Issue by drandre2014** [greyblake/vim-esperanto#2]

**Comment by greyblake** [comment]
Hi.Thanks for the opening the issue.
Mapping has nothing to do with converting of already existing text. And if such feature would be implemented, it would be totally unexpected behavior for most of the users.

If you want the converting functionality, it can be implemented with a command. If you really need this please open another issue.

**Comment by drandre2014** [comment]
What command would best accomplish convert x-/h-style orthography?
